Eppo-exp/js-client-sdk

- README.md
- package.json
- src/eppo-client.ts
- src/shard.ts
- webpack.config.js
- yarn.lock
---
---
Fixes Eppo-exp/eppo#4083
I have added a webpack config that allows the SDK to be loaded [from a CDN (JSDelivr)](https://www.jsdelivr.com/package/npm/@eppo/js-client-sdk). This makes it possible for consumers to load the SDK with a `<script>` tag like so:
```
<script src="https://cdn.jsdelivr.net/npm/@eppo/js-client-sdk@0.0.5/dist/eppo-sdk.min.js"></script>
```
Full example:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Eppo JS Client SDK</title>
<script src="https://cdn.jsdelivr.net/npm/@eppo/js-client-sdk@0.0.5/dist/eppo-sdk.min.js"></script>
</head>
<body>
<script type="module">
function main() {
const …
```
> Add Webpack Config

- package.json
- src/eppo-client.spec.ts
- src/eppo-client.ts
- src/index.ts
---
---
https://www.notion.so/eppo/Null-assignments-with-JS-Client-SDK-4263f4bca87646e5911c2d6be12b80fd
Disabled sticky sessions for the reasons described in the above notion doc. It can be confusing because, if getAssignment is called before initialization, null is returned for the duration of the session.
- Refreshing the page after the cache TTL expires causes the new variation to load
- Only one request occurs per cache TTL period (10 minutes, or 3 minutes with the updated TTL)
[//]: # (Add one …
> Revert Sticky Sessions

- .github/workflows/publish.yml
- README.md
Currently the SDK release process is manual;requires running `npm publish` from terminal.
Added a GitHub workflow to publish to NPM whenever a new GitHub release is created. It only publishes if the version is different than what's currently on NPM. Used [this github action](https://github.com/marketplace/actions/npm-publish)
> GitHub workflow to publish to NPM

- Makefile
- package.json
- src/index.spec.ts
- test/testHelpers.ts
- yarn.lock
---
---
Fixes: [FF-858](https://linear.app/eppo/issue/FF-858/update-javascript-sdk-with-allocation-key)
> Update eppo js commons dependency to v1.4.1 to include allocation key in logged event's experiment attribute (FF-858) 

- .github/workflows/publish.yml
---
---
Still failing to publish, with a new error: https://github.com/Eppo-exp/js-client-sdk/actions/runs/6279038634/job/17054001216
```
10s
Run yarn install
yarn install v[1](https://github.com/Eppo-exp/js-client-sdk/actions/runs/6279038634/job/17054001216#step:4:1).22.19
[1/[4](https://github.com/Eppo-exp/js-client-sdk/actions/runs/6279038634/job/17054001216#step:4:5)] Resolving packages...
[2/4] Fetching packages...
error husky@8.0.1: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.12"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for …
```
> Bump node version to 18.x

- package.json
- yarn.lock
We need to upgrade semver to:
* `>= 7.5.2`
* `>= 6.3.1`
This is blocked by our current jest version
after updating we see that:
* the 6 branch is all on `6.3.1`
* 7 branch is on `7.5.4`
```
➜  js-client-sdk git:(lr/upgrade/jest) ✗ yarn why semver
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "semver"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "semver@7.5.4"
info Has been hoisted to "semver"
info Reasons this module exists
- Hoisted from "ts-jest#semver"
- Hoisted from "ts-loader#semver"
- Hoisted from …
```
> upgrade jest to 29.7.0 to resolve vulnerability in semver

- package.json
- src/index.ts
- yarn.lock
---
---
Fixes: EPD-1930
Vanta shows a security issue:
https://github.com/Eppo-exp/js-client-sdk/security/dependabot/12
- upgrade js-client-sdk-common
- upgrade axios itself
- some fixes for js-client-sdk-common:2.0.0
With `yarn why axios`:
```
(base) pavel@Pavels-MacBook-Pro-2 js-client-sdk % yarn why axios
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "axios"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "axios@1.6.2"
info Has been hoisted to "axios"
info …
```
> EPD-1930 upgrade @eppo/js-client-sdk-common and axios versions

- package.json
- src/index.spec.ts
- src/index.ts
- src/local-storage-assignment-cache.ts
- src/local-storage.ts
- yarn.lock
---
---
Downstream related change: https://github.com/Eppo-exp/js-client-sdk-common/pull/33 enables passing an implementation.
The goal is for users of Eppo's SDK in the browser to remove duplicate assignments within and now between sessions.
We are creating a cache based on `LocalStorage` which is a unique API to browsers.
* Use only a single `LocalStorage` key for the entire assignment cache - it is always for a single subject.
* Instantiate the js client with this cache.
* New integration test. …
> Adds LocalStorageAssignmentCache with persistent implementation between sessions to lower assignment logging; enabled by default (FF-839)

- package.json
- yarn.lock
---
---
Bump the version of @eppo/js-client-sdk-common to include the base64 bug fix, see https://github.com/Eppo-exp/js-client-sdk-common/pull/41
> Bump @eppo/js-client-sdk-common to 2.2.1

- package.json
- yarn.lock
---
---
* drops `lru-cache` external dependency; allows for an upgrade path for blocked customers
next steps: integrate into eppo app before customer notification
> bump commons to 2.2.3

- package.json
- src/configuration-factory.ts
- src/index.spec.ts
- src/index.ts
- src/local-storage-assignment-cache.spec.ts
- src/local-storage-assignment-cache.ts
- src/local-storage.spec.ts
- src/local-storage.ts
- yarn.lock
…torage (FF-1980)
* Prepare for user provided persistence stores
* 🐞 Fixes bug where stale keys in `localStorage` were not being removed. All configuration is stored to a single key.
* bump to `commons:3.0.6`
* `LocalStorageBackedAsyncStore` implementation of `IAsyncStore` - while `localStorage` is a sync API, wrap the requests in promises to fit in with our design pattern of persistence stores all being async.
* 🐞 Fixes bug where stale keys in `localStorage` were not being removed. All configuration is stored to a single key.
* `configurationStorageFactory` detects what environment it is executing in and creates the appropriate configuration store.
[//]: # (Please describe in …
> bump to commons 3.0.6; add LocalStorageBackedAsyncStore (FF-1980)

- package.json
- src/chrome.configuration-store.spec.ts
- src/configuration-factory.ts
- src/index.ts
- src/local-storage-assignment-cache.ts
- src/local-storage.spec.ts
- src/local-storage.ts
- test/testHelpers.ts
- tsconfig.json
---
---
1️⃣  Omitting calling the `init` method on the `IConfigurationStore` means that the `servingStore` is not populated from whatever is present on disk (localStorage, chrome.storage, etc).
Throttling the browser network demonstrates that the flags don't begin evaluating to `true` until after the network request completes, whereas the desired behavior is already locally cached flags should start being evaluated as soon as the disk cache is loaded into memory, before the network request:
https://github.com/Eppo-exp/js-client-sdk/assets/57361/ac3a610c-02c0-4709-8555-ab3427988286
2️⃣ If the persistent store is `null`, …
> initialize the configuration store

- docs/js-client-sdk.chromestorageengine._constructor_.md
- docs/js-client-sdk.chromestorageengine.md
- docs/js-client-sdk.eppojsclient.getbooleanassignment.md
- docs/js-client-sdk.md
- js-client-sdk.api.md
- package.json
- src/index.spec.ts
- src/index.ts
- webpack.config.js
- yarn.lock
_Eppo Internal:_
🎟️ **Ticket:** [FF-2282 - JS Client SDK - Fix or omit source maps](https://linear.app/eppo/issue/FF-2282/js-client-sdk-fix-or-omit-source-maps)
🗨️ **Slack:** "...The first issue is when running our web client app locally with a webpack dev server, the @eppo/js-client-sdk and @eppo/js-client-sdk-common outputs a lot of warnings..."(https://eppo-group.slack.com/archives/C06TTCBDRU4/p1717092945766289?thread_ts=1717091604.044459&cid=C06TTCBDRU4)
When using [`source-map-loader`](https://webpack.js.org/loaders/source-map-loader/) with Wepback, it throws many warnings because it cannot map back to the TypeScript source with what is provided in the `dist` directory.
To fix this, we include the non-test TypeScript source files as well, so that source maps work.
Note that when a …
> Generate separate (vs. inline) source map files

- package.json
_Eppo Internal:_ 
🎟️ **Ticket:* [FF-2505 - Could not find a declaration file for module](https://linear.app/eppo/issue/FF-2505/could-not-find-a-declaration-file-for-module)
🗨️ **Slack:* ["...signals about the declaration file being missing..."](https://eppo-group.slack.com/archives/C04KR1GGE3C/p1719233938647939)
Typescript allows including type information with an npm package using the `types` (or `typings`) field in `package.json`. ([docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package))
However, our entry for this field pointed to a non-existent file, which would result in typescript-loader generate the following warning error:
```
[tsl] ERROR in /Users/aaron/Workspace/webpack-demo/src/index.ts(2,38)
TS2307: …
```
> Have package.json point to correct type file

- package.json
- src/index.ts
---
---
Should be honoring the settings from `applicationLogger` - by default no browser logs.
👉 In the future we should allow users to set their desired level.
> bug: [replace all console messages with applicationLogger] (FF-2552)

- package.json
- src/cache/chrome-storage-assignment-cache.ts
- src/chrome-storage-engine.spec.ts
- src/configuration-factory.spec.ts
- src/index.spec.ts
- src/index.ts
- src/isolatable-hybrid.store.spec.ts
- src/local-storage.store.spec.ts
- src/string-valued.store.ts
- yarn.lock
_Eppo Internal_:
🎟️ **Ticket:** [FF-2560 - Update Client SDK for Updated Common SDK](https://linear.app/eppo/issue/FF-2560/update-client-sdk-for-updated-common-sdk)
Some changes made to the shared common SDK affect our client SDK, even if it's not using bandits. These include:
* Additional configuration store parameters for constructing the client
* Renamed the flag store and assignment logger for clarity now that we have bandit stores and loggers
This PR updates uses the latest common SDK and address the above issues. 💪 
It also handled an unrelated rename and fixed a flakey test. 🧹
> Update for updated common SDK

- .vscode/settings.json
- package.json
- src/index.spec.ts
- src/index.ts
- src/isolatable-hybrid.store.ts
- yarn.lock
[Evaluation Reasons - js-client-sdk-common](https://github.com/Eppo-exp/js-client-sdk-common/pull/97)
**Evaluation Reasons - js-client-sdk**
[Evaluation Reasons - node-server-sdk](https://github.com/Eppo-exp/node-server-sdk/pull/62)
[Evaluation Reasons - react-native-sdk](https://github.com/Eppo-exp/react-native-sdk/pull/51)
This implements the "assignment details" functionality for the js-client-sdk. 
- `IEppoClient` is being removed in `@eppo/js-client-sdk-common@3.4.0`, which required updates
- `IConfigurationStore.setEntries` returns `Promise<boolean>` in `@eppo/js-client-sdk-common@3.4.0` which also requires updates. Resolving with `true` internally tells the configuration store to set the `configFetchedAt` and `configPublishedAt` fields.
Manual testing will be done once …
> feat: Evaluation Details

- .github/workflows/lint-test-sdk.yml
- Makefile
🎟️ Fixes FF-3092 towards FF-3085
👯‍♂️ **Related PRs**
- [sdk-test-data#58](https://github.com/Eppo-exp/sdk-test-data/pull/58)
- [java-server-sdk#75](https://github.com/Eppo-exp/java-server-sdk/pull/75)
- [python-sdk#65](https://github.com/Eppo-exp/python-sdk/pull/65)
Changes are often made to the [sdk-test-data](https://github.com/Eppo-exp/sdk-test-data) repository to capture new behaviours, bugs and edge cases. When these changes are pushed to `main`, the SDKs are cloned locally (locally to the github action running) and their respective tests are run. These tests are set up and run by copies of the SDK test workflows - see [sdk-test-data workflow](https://github.com/Eppo-exp/sdk-test-data/blob/main/.github/workflows/test-sdks.yml). There are a number of limitations to this setup:
- Test …
> quality: parameterize branch names and make test

- jest.config.ts
- package.json
- src/events/browser-network-status-listener.spec.ts
- src/events/browser-network-status-listener.ts
- src/events/local-storage-backed-named-event-queue.spec.ts
- src/events/local-storage-backed-named-event-queue.ts
- src/i-client-config.ts
- src/index.spec.ts
- src/index.ts
- src/util.ts
- tsconfig.json
- yarn.lock
Towards: FF-3608
Towards: FF-3609
Hook into https://github.com/Eppo-exp/js-sdk-common/pull/139 to use new event dispatcher API
Integrate new event tracking API
Wrote tests
> feat(events): Use new event dispatcher API

- package.json
- yarn.lock
Bump `js-client-sdk-common` to pick up fix https://github.com/Eppo-exp/js-sdk-common/pull/153
As above
Existing tests
> chore: Bump js-client-sdk-common version

- package.json
- webpack.config.js
- yarn.lock
---
---
Fix `process is not defined` error
https://github.com/Eppo-exp/js-sdk-common/pull/136 introduced a change to `applicationLogger` that added a check for `process.env.LOG_LEVEL`.
This doesn't work on the browser because `process` only exists in the Node environment.
Although there's a tricky reason why the original `(process.env.NODE_ENV === 'production' ? 'warn' : 'info')` expression didn't already fail, which is that webpack resolves the entire expression to simply `warn` since it resolves `process.env.NODE_ENV` to `production` at build time.
I've worked around it by doing a similar preprocessing step for `LOG_LEVEL` by adding a `webpack.DefinePlugin` to the webpack config that …
> fix: Set `process.env.LOG_LEVEL` to `null` in webpack config + Buffer polyfill

- docs/js-client-sdk.buildstoragekeysuffix.md
- docs/js-client-sdk.iclientconfigsync.md
- docs/js-client-sdk.md
- js-client-sdk.api.md
- src/chrome-storage-engine.ts
- src/index.ts
---
---
Removes the following `ae-missing-release-tag` warnings when `api-extractor` runs
```
Warning: src/chrome-storage-engine.ts:15:1 - (ae-missing-release-tag) "ChromeStorageEngine" is part of the package's API, but it is missing a release tag (@alpha, @beta, @public, or @internal)
Warning: src/index.ts:37:1 - (ae-missing-release-tag) "IClientConfigSync" is part of the package's API, but it is missing a release tag (@alpha, @beta, @public, or @internal)
Warning: src/index.ts:238:1 - (ae-missing-release-tag) "buildStorageKeySuffix" is part of the package's API, but it is missing …
```
> chore: Clean up missing release tag warnings

- package.json
- src/events/local-storage-backed-named-event-queue.ts
- src/i-client-config.ts
- src/index.spec.ts
- src/index.ts
- yarn.lock
_Eppo Internal:_
🎟️ **Ticket:** [FF-3767 - Update JS Client to use updated Common JS for special character handling](https://linear.app/eppo/issue/FF-3767/update-js-client-to-use-updated-common-js-for-special-character)
🗨️ **Slack Thread:** ["...flag text encoding problem..."](https://eppo-group.slack.com/archives/C0541NTN6QH/p1735566355776199)
👯 **Related PR:** [`js-sdk-common #187`](https://github.com/Eppo-exp/js-sdk-common/pull/187)
SDKs need to be able to handle special, non-ASCII characters. This PR adds a test that checks that by using strings with characters from a variety of languages as well as emojis, which all have non-ASCII values.
We update our common module which switches from using [`js-base64`](https://www.npmjs.com/package/js-base64)'s `btoaPolyfill()` and …
> Bump common version to allow handling of special characters

- src/i-client-config.ts
- src/index.ts
Allow providing a `maxSize` configuration for `BoundedEventQueue`.
This code path is only hit when `localStorage` is not available, which should be the "unhappy" path. In that case, we want to allow keeping more than 100 events in memory (`MAX_EVENT_QUEUE_SIZE`)
Didn't write a test since it's trivial, but I can if folks feel like it's important enough
> feat(events): Allow providing a `maxQueueSize` configuration

- docs/js-client-sdk.iprecomputedclientconfigsync.md
- docs/js-client-sdk.md
- src/index.spec.ts
- src/index.ts
---
---
We noticed an uncaught exception when `precomputedConfiguration` is an empty string. To be consistent with the online `precomputedInit`, this function should also always return an instance if `throwOnFailedInitialization` is `false`
> fix: allow empty string for precomputedConfiguration

- package.json
- src/configuration-factory.ts
- src/index.ts
---
---
Initializing bandit store for the offline init.
> add memory-only bandit configuration store for offline client.

- src/index.ts
> fix: missing bandit store for precomputedInit

- src/index.spec.ts
- src/index.ts
---
---
Some feedback [in a previous PR](https://github.com/Eppo-exp/js-sdk-common/pull/164#discussion_r1905896857) that we should avoid overwriting the Eppo client instance.
> We shall prefer creating a new instance of the client in initialization instead of resetting the existing one.
This is challenging because it breaks the expected behavior that `getPrecomputedInstance` always returns an instance of `EppoPrecomputedClient`.
https://github.com/Eppo-exp/js-client-sdk/blob/f5d4eb4c9ccf1475bee47f79ee5900a3a18cddee/src/index.ts#L784-L786
It would be `undefined` before any of the initialization functions (`precomputedInit` …
> fix: getprecomputedinstance should always return an instance

- js-client-sdk.api.md
- package.json
- yarn.lock
---
---
Adds fixes from: https://github.com/Eppo-exp/js-sdk-common/pull/202
> chore: bump commons to 4.8.3-alpha.5

- .github/workflows/lint-test-sdk.yml
---
---
_Eppo Internal_
🎟️ 
Fixes: [FF-3866](https://linear.app/eppo/issue/FF-3866/js-client-tests-are-failing-when-run-in-sdk-test-data)
The testing workflow is reused remotely in the *sdk-test-data* repository. To make these workflows reusable, the repository and branch must be specified for the checkout action otherwise, the default of `sdk-test-data` will be used (since the action runs in the sdk-test-data repository)
- reintroduce the parameters that were dropped in #101 
- Triggered the tests from the sdk-test-data repo.
https://github.com/Eppo-exp/sdk-test-data/actions/runs/12938159310/job/36087690316
> fix: use repo and ref parameters in checkout action

- src/index.spec.ts
- test/testHelpers.ts
The js-client UFC tests are failing when an expected assignment is the empty string. Upon investigation, this is failing because of a well intentioned check of the assignment result. This check fails when the assignment is an empty string (and likely when the assignment is intentionally false but we haven't test cases to cover this).
Ultimately, the bug lies in the testing harness, not the core code, as the node server and js-common SDKs do not fail in this manner.
- remove the truthy check; don't fallback on default value as the EppoClient handles that.
- update to use `getBoolean` instead of deprecated `getBool`
> fix: don't fallback to default value in test harness

- docs/js-client-sdk.init.md
- docs/js-client-sdk.md
- package.json
- src/index.spec.ts
- src/index.ts
---
---
The precompute client needs the assignment cache to dedupe assignments. This is central functionality of the SDKs, not a nice-to-have
Scope of work:
> feat: assignment cache to dedupe logging by the precomputed client

- docs/js-client-sdk.eppojsclient.initialized.md
- docs/js-client-sdk.eppojsclient.instance.md
- docs/js-client-sdk.eppojsclient.md
- docs/js-client-sdk.getinstance.md
- docs/js-client-sdk.init.md
- docs/js-client-sdk.md
- js-client-sdk.api.md
- package.json
- src/index.ts
---
---
_Eppo Internal_
🎟️ towards FF-3888
📜 [Multiple Eppo Clients](https://www.notion.so/eppo/Multiple-concurrent-and-isolated-EppoClient-instances-running-within-an-application-18449cc0114380288eb3eaac580c4e53)
[Configuration Side-loading](https://www.notion.so/eppo/Configuration-side-loading-design-12249cc0114380bc9650d8dc4e189e77)
**This PR is carved from #166 in an attempt to make #166 focused on the the "new" API.** This PR adds no net new functionality, however, the new `EppoJSClient.init` method, marked **@internal** does allow for unbuffered initialization calls just as the global `init` method previously allowed. This internal method can be made private once we remove the global `init` method in …
> chore: move initialization into class methods, limit singleton use

- docs/js-client-sdk.eppojsclient.instance.md
- docs/js-client-sdk.eppojsclient.md
- js-client-sdk.api.md
- package.json
- src/index.spec.ts
- src/index.ts
- yarn.lock
A recent change to the common package moved the source-of-truth of obfuscation to config store metadata (via format). The EppoJS client and its tests require updating to ensure the format metadata is being used instead of the deprecated internal isObfuscated field. 
- update to latest common
- minor bump to `3.12.0`
- set default format metadata where needed
- update tests to use an obfuscated config file (common package caches whether config is obfuscated)
- docs
- no functional changes
> chore: update to latest common.

- js-client-sdk.api.md
- package.json
- src/index.ts
- yarn.lock
* Bump js-common-sdk to v4.13.0
* Export new API `EppoAssignmentLogger`
* Bring it on par with its counterpart https://github.com/Eppo-exp/node-server-sdk/pull/97 in node-server-sdk
> chore: Prepare for v3.13.0 releaes

- package.json
- src/index.spec.ts
- src/index.ts
- yarn.lock
- Upgrades to js-common@4.15.1 see _[release notes](https://github.com/Eppo-exp/js-sdk-common/releases/tag/v4.15.1)_
- adds tests to verify CDN target.
> chore: Upgrade to js-client-sdk-common@4.15.1

- package.json
- src/index.spec.ts
- src/index.ts
---
---
_Eppo Internal_
[//]: #  (Link to the issue or doc corresponding to this chunk of work)
🎟️ Fixes: [FF-4344 - Ensure JS Client offline init sets config published and fetched at](https://linear.app/eppo/issue/FF-4344/ensure-js-client-offline-init-sets-config-published-and-fetched-at)
👯 **Related PR:** [`eppo #12880`](https://github.com/Eppo-exp/eppo/pull/12880)
Evaluation details include the dates the configuration was published and fetched. However, when offline initialized, these need to be provided.
Add the publish and fetch dates for the configuration as optional parameters for the synchronous client configuration, and then set them to the underlying offline init memory store
not needed; bugfix
* Added a test case to `index.spec.ts`
* Installed this branch in …
> Ability to specify configuration dates with offline init

- package.json
- src/index.ts
---
---
_Eppo Internal_
[//]: #  (Link to the issue or doc corresponding to this chunk of work)
🎟️ Fixes: [FF-4383 - JS Precomputed client warns not initialized despite being initialized](https://linear.app/eppo/issue/FF-4383/js-precomputed-client-warns-not-initialized-despite-being-initialized)
Our precomputed client warns that it's not initialized when it is, which can cause confusion.
The reason is that it was checking the wrong static class for the initialized boolean
Used `eppo-precomputed-client.spec.ts`. Saw the warning, made the fix, no more warning.
> Use right class for static initialization check
